nohup python3 -u main.py -d 'hr' -i 0 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log0_hr_offset_02_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 1 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log1_hr_offset_02_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 2 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log2_hr_offset_02_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 3 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log3_hr_offset_02_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 4 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log4_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 5 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log5_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 6 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log6_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 7 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log7_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 8 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log8_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 9 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log9_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 10 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log10_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 11 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log11_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 12 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log12_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 13 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log13_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 14 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log14_hr_offset_02_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 15 -h 'offset_02' -r 'standard' -c 0 -n True -w '' > ../logs/log15_hr_offset_02_standard_nomodels.out &

nohup python3 -u main.py -d 'hr' -i 0 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log0_hr_offset_01_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 1 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log1_hr_offset_01_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 2 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log2_hr_offset_01_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 3 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log3_hr_offset_01_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 4 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log4_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 5 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log5_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 6 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log6_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 7 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log7_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 8 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log8_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 9 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log9_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 10 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log10_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 11 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log11_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 12 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log12_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 13 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log13_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 14 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log14_hr_offset_01_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 15 -h 'offset_01' -r 'standard' -c 0 -n True -w '' > ../logs/log15_hr_offset_01_standard_nomodels.out &

nohup python3 -u main.py -d 'hr' -i 0 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log0_hr_biased_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 1 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log1_hr_biased_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 2 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log2_hr_biased_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 3 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log3_hr_biased_standard_nomodels.out &
nohup python3 -u main.py -d 'hr' -i 4 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log4_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 5 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log5_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 6 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log6_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 7 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log7_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 8 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log8_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 9 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log9_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 10 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log10_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 11 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log11_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 12 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log12_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 13 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log13_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 14 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log14_hr_biased_standard_nomodels.out &
#nohup python3 -u main.py -d 'hr' -i 15 -h 'biased' -r 'standard' -c 0 -n True -w '' > ../logs/log15_hr_biased_standard_nomodels.out & 