nohup python3 -u main.py -d 'hr' -i 0 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log0_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 1 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log1_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 2 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log2_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 3 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log3_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 4 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log4_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 5 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log5_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 6 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log6_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 7 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log7_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 8 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log8_fico_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 9 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log9_fico_offset01_standard_cost02.out &

nohup python3 -u main.py -d 'hr' -i 0 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log0_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 1 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log1_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 2 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log2_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 3 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log3_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 4 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log4_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 5 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log5_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 6 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log6_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 7 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log7_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 8 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log8_fico_biased_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 9 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'tr-no(ADB),tr2stage' > ../logs/log9_fico_biased_standard_cost02.out &

nohup python3 -u main.py -d 'hr' -i 0 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log0_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 1 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log1_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 2 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log2_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 3 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log3_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 4 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log4_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 5 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log5_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 6 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log6_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 7 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log7_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 8 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log8_fico_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'hr' -i 9 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'tr-no(ADB),tr2stage' > ../logs/log9_fico_biasedDec_standard_cost02.out &
