nohup python3 -u main.py -d 'heart_disease' -i 10 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log10_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 11 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log11_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 12 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log12_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 13 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log13_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 14 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log14_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 15 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log15_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 16 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log16_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 17 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log17_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 18 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log18_heart_disease_offset01_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 19 -h 'offset_01' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log19_heart_disease_offset01_standard_cost02.out &

nohup python3 -u main.py -d 'heart_disease' -i 10 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log10_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 11 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log11_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 12 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log12_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 13 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log13_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 14 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log14_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 15 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log15_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 16 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log16_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 17 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log17_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 18 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log18_heart_disease_biased_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 19 -h 'biased' -r 'standard' -c 0.2 -n False -p '' -b False -w 'hyrs,tr' > ../logs/log19_heart_disease_biased_standard_cost02.out &

nohup python3 -u main.py -d 'heart_disease' -i 10 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log10_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 11 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log11_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 12 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log12_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 13 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log13_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 14 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log14_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 15 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log15_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 16 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log16_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 17 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log17_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 18 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log18_heart_disease_biasedDec_standard_cost02.out &
nohup python3 -u main.py -d 'heart_disease' -i 19 -h 'biased' -r 'standard' -c 0.2 -n False -p '_dec_bias' -b True -w 'hyrs,tr' > ../logs/log19_heart_disease_biasedDec_standard_cost02.out &